### ISSUE TITLE
copy-paste does not always work in the terminal

### ISSUE THREAD

**Issue by camilleminaudo** [SwissDataScienceCenter/renku-jupyter#24]
This is probably out of the scope of renku-notebooks, however it would be good to track it somehow - especially when it gets fixed:
* although copy-paste, using tab etc work fine in the notebook itself, they don't behave as usual when under the terminal; combining with need for long URLs and branch names, this is a killer (resulting in using ubuntu environment elsewhere, instead of where work should be).

Is there any remedy/workaround or timeline to check it again?
This has occurred today with windows/chrome combo but it affects others, too.

**Comment by rokroskar** [comment]
@camilleminaudo have you had a chance to try the fix described in the link I posted above?

**Comment by rokroskar** [comment]
closing this for now - please report back if the problem persists.
