### ISSUE TITLE
Provide method to overlay user preferences in project repositories

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku-jupyter#26]
Users would like to customize and save their preferences, so that they do not have to reconfigure their preference files each time they restart a jupyter notebook docker. They also would like to use the same customized preferences between projects.

Preferences include short-cuts etc, such as Rstudio UI preferences.

Preferences can be located in the home directory (.config) or in the repository itself.

Preferences can be global defaults, or specific to a project, or a class of projects. They can also be specific to a particular user, or a group of users.

Preferences are not something we necessarily like to share between developers and should not be saved in the git repository. Nobody likes to inherit someone's else preferences after a git pull (they normally end up in the gitignore). The exception is if the preferences are used to enforce a specific style of programming or a standard style of visualizing results etc for a group of collaborators.

It would be nice when a Jupyter notebook is started to look up a database of preferences using the above criterions (e.g. using tags, or selection patterns with priority levels to manage conflicts), and automatically apply preference overlays in the docker container after the git clone, in a way that does not interfere with the content of the git repository.

**Comment by rokroskar** [comment]
This was done in #65
