### ISSUE TITLE
Displaying PyViz objects in Jupyter lab

### ISSUE THREAD

**Issue by aleva85** [SwissDataScienceCenter/renku-jupyter#32]
I can't generate an interactive graph using the python bokeh module.

Error message in popup is "Displaying PyViz objects in Jupyter lab requires the jupyter_pyviz extension to be installed", but the installation didn't work for me.

Detailed error report here: https://docs.google.com/document/d/1wSh6lizKWfNcZUfK_LZVuaDn3-fV-QPV-P-lgOlBYBk/edit

**Comment by rokroskar** [comment]
Hi @aleva85 I'm able to add the extension and get this:

![image](https://user-images.githubusercontent.com/3353586/57783866-30f45d00-772f-11e9-818c-0cfea3d86d99.png)

The change needed is to add the line

```
RUN jupyter labextension install @pyviz/jupyterlab_pyviz
```

to the `Dockerfile` in your project. Make sure you wait until the notebook image build is finished before you try launching a notebook. 

Let me know if it works for you!

**Comment by rokroskar** [comment]
Hi @aleva85 did you have a chance to try this out?

**Comment by aleva85** [comment]
Hi @rokroskar, sorry I took so long. I made a new project and with that line in the docker file everything worked.
I also tried to get back to the original project and there it just takes forever to launch the server. I must be making something wrong. 
Anyway, thanks for looking into it, and hope it was useful.

**Comment by rokroskar** [comment]
No worries, glad it worked!
