### ISSUE TITLE
ensure that the RStudio session goes to the correct working directory

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-jupyter#47]
RStudio defaults to setting the working directory to the user's home directory - instead, we should set the working directory to be where we are cloning the project. Ideally, we could do this dynamically when the rstudio session is launched.

**Comment by rokroskar** [comment]
Did we decide that this was not a priority for the moment? @cchoirat ?

**Comment by cchoirat** [comment]
Does it boil down to opening the Rproj file by hand in RStudio?  If so,
yes, it can wait.

**Comment by rokroskar** [comment]
yes, you have to find your project in `/work`

**Comment by cchoirat** [comment]
fine for now then

**Comment by rokroskar** [comment]
We decided to just provide a symlink to the project directory for now
