### ISSUE TITLE
bug: user is asked to git config for R docker image

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-jupyter#58]
Spawning a notebook and connecting to RStudio from the R base docker image (change the `/lab` endpoint to `/rstudio` after spawning the notebook), the renku commands are stuck trying to get the user to git config. This is not an issue using the Python base docker images.

```
$ renku dataset create test
Error: The user name and email are not configured. Please use the "git config" command to configure them.
        git config --global --add user.name "John Doe"
        git config --global --add user.email "john.doe@example.com"
```

**Comment by rokroskar** [comment]
ah I thought I fixed this - maybe I did it in a project but not in the base image. It can be solved in the entrypoint. See https://renkulab.io/projects/960/files/blob/entrypoint.sh

**Comment by emmjab** [comment]
This is fixed! (not sure which commit but I tested it by `renku dataset create test` in the latest `renku-project-template` in renkulab)
