### ISSUE TITLE
Inject user preferences into the environment

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-jupyter#64]
# Description

Users want to be able to set up an environment configuration that moves with them. Examples of what may be in here include:
* .bashrc
* Jupyter font sizes

# Solution

Add code to the docker entrypoint that looks for a repo in gitlab that conforms to a naming convention which includes the user's name. If it is found, copy over and append the configuration files into the environment.

Document the process in the renku documentation.

**Comment by emmjab** [comment]
doc issue is here: https://github.com/SwissDataScienceCenter/renku/issues/713
