### ISSUE TITLE
git user/email not picked up by the git jupyterlab extension

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-jupyter#71]
When trying to make a commit using the git jupyterlab extension, the user is prompted for a name and email, even though those have been added to the git configuration. 

<img width="568" alt="image" src="https://user-images.githubusercontent.com/3353586/74389294-0a6a6c00-4dfe-11ea-990e-aafc160c0780.png">

**Comment by emmjab** [comment]
A note -- it turns out if you double click on the jupyterlab terminal (but don't need to type anything in), the git jupyterlab extension gets pre-configured with the stuff in git config.

The pop up to fill in git config information only occurs if you don't open the terminal.

**Comment by rokroskar** [comment]
Might be worth opening an issue with them?

**Comment by emmjab** [comment]
Ok -- before making the issue I realized I forgot to swap out for the latest docker image; with the new one (and presumably newest version of jupyterlab-git), `FROM renku/singleuser:085b7e7-renku0.9.0`, this issue doesn't appear to happen anymore 😃!!!
https://stable.dev.renku.ch/projects/e.jablonski/test-jupyter-gui/files/blob/Dockerfile
